name: Test pardot id fix with Dockerx

on:
  push:
    workflow_dispatch:
    branches:
      - "test/fix/pardot-id"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          version: v0.5.1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push OSS image
        run: |
          docker buildx build --push \
            --tag hasancelik/hazelcast:pardot \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-oss

      - name: Build/Push EE image
        run: |
          docker buildx build --push \
            --tag hasancelik/hazelcast-enterprise:pardot \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x hazelcast-enterprise